---
- name: Check current docker-compose version.
  command: "{{ docker_compose_path }} --version"
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: Install Docker Compose (if configured).
  shell: |
    wget -q {{ docker_compose_url }} -O {{ docker_compose_path }}
    chmod +x {{ docker_compose_path }}
  args:
    chdir: /tmp
  when: >
    docker_compose_current_version.stdout is not defined
    or docker_compose_version not in docker_compose_current_version.stdout
